### ISSUE TITLE
build: open Gomfile: no such file or directory

### ISSUE THREAD

**Issue by thomas-mc-work** [remeh/mehtadata#2]
I followed the instructions form the mehstation wiki to build the project:

```
git clone https://github.com/remeh/mehtadata
cd mehtadata
mkdir gopath
export GOPATH=$(pwd)/gopath
go get github.com/mattn/gom
$GOPATH/bin/gom install
$GOPATH/bin/gom build
```

When I launch `$GOPATH/bin/gom install` then I get this error message: `gom:  open Gomfile: no such file or directory`.

I guess that `go get github.com/mattn/gom` shall get the Gomfile, but it doeesn't seem to do anything. Invoking this command doesn't provide any output (which is good normally) and the status code is `0`.

**Comment by remeh** [comment]
Hello Thomas! Sorry about that, it's in my todolist to update the wiki...
The procedure has changed and it's actually now much simplier to compile mehtadata:

```
mkdir gopath
export GOPATH=$(pwd)/gopath
go get github.com/remeh/mehtadata
cp gopath/bin/mehtadata .
```

And the binary mehtadata will be available in the current directory.
I'll update the wiki page asap.

**Comment by thomas-mc-work** [comment]
:+1: Thank you!
